# Generated by Django 3.2.5 on 2022-06-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('programming_language', models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Java')], max_length=100)),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Expert')], max_length=100)),
                ('duration', models.CharField(choices=[('1', '<1 year'), ('2', '1-3 years'), ('3', '>3 years')], max_length=100)),
                ('time', models.IntegerField()),
                ('last_used', models.IntegerField()),
                ('fuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.demographic')),
            ],
        ),
    ]
