# Generated by Django 3.2.5 on 2022-06-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='fuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographic_id', to='api.demographic'),
        ),
    ]
