# Generated by Django 3.2.5 on 2022-06-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expertise_fuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='fuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.demographic'),
        ),
    ]
