# Generated by Django 3.2.5 on 2022-06-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('code_image', models.ImageField(upload_to='')),
                ('fqbid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionbank')),
            ],
        ),
    ]
