# Generated by Django 3.2.5 on 2022-06-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_time',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=500, null=True)),
                ('option2', models.CharField(max_length=500, null=True)),
                ('option3', models.CharField(max_length=500, null=True)),
                ('option4', models.CharField(max_length=500, null=True)),
                ('correct_option', models.CharField(max_length=500, null=True)),
                ('marks', models.FloatField(null=True)),
                ('question_time', models.IntegerField()),
                ('fcid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.code')),
            ],
        ),
    ]
