# Generated by Django 3.2.5 on 2022-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220603_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.IntegerField(null=True),
        ),
    ]
