# Generated by Django 3.2.5 on 2022-06-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_evaluation_questionbankevaluation_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbankevaluation',
            old_name='evid',
            new_name='fevid',
        ),
    ]
