# Generated by Django 3.2.5 on 2022-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_evid_questionbankevaluation_fevid'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
