# Generated by Django 3.2.5 on 2022-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='decision',
            field=models.CharField(choices=[('1', 'Correct'), ('2', 'Incorrect')], max_length=100, null=True),
        ),
    ]
