# Generated by Django 3.2.5 on 2022-06-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_score_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='code_read_time',
        ),
        migrations.RemoveField(
            model_name='code',
            name='question_read_time',
        ),
        migrations.AlterField(
            model_name='expertise',
            name='last_used',
            field=models.DateField(),
        ),
    ]
