# Generated by Django 3.2.5 on 2022-06-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0005_alter_expertise_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='last_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
