# Generated by Django 3.2.5 on 2022-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0006_alter_expertise_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='last_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
